# Generated by Django 5.2.17 on 2026-08-25 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_missing_profiles(apps, schema_editor):
    user_model = apps.get_model("auth_app", "User")
    profile_model = apps.get_model("profile_app", "Profile")
    existing_user_ids = profile_model.objects.values_list("user_id", flat=True)
    missing_users = user_model.objects.exclude(pk__in=existing_user_ids)
    profile_model.objects.bulk_create(
        profile_model(user=user) for user in missing_users
    )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='profiles/')),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('tel', models.CharField(blank=True, default='', max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('working_hours', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username'],
            },
        ),
        migrations.RunPython(
            create_missing_profiles,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
